### ISSUE TITLE
bad adaptive icon on 8.1.0 (LNGOS 15.1)

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [TeamAmaze/AmazeFileManager#1493]
![afm](https://user-images.githubusercontent.com/14617699/47882941-3990e000-de3c-11e8-90db-c52f4bb7dfc1.png)

Android version 8.1.0
LineageOS version: 15.1-201810

**Comment by c-e-p-x-u-o** [comment]
you should fix it to upload new version to google play
https://www.xda-developers.com/google-play-app-updates-must-target-android-8-0/

**Comment by 532910** [comment]
Any update? v3.3.4 from GPlay still not adaptive:
![image](https://user-images.githubusercontent.com/14617699/69190336-3d6bcf00-0b31-11ea-821f-d9fcf2019199.png)

**Comment by 532910** [comment]
Switched to https://github.com/zhanghai/MaterialFiles
Unsubscribing
