### ISSUE TITLE
File copy operation is paused when the phone goes in stand by mode

### ISSUE THREAD

**Issue by bugnano** [TeamAmaze/AmazeFileManager#1572]
When I'm copying a large file using SFTP, the process can take more than 1 minute, so the phone goes in stand by mode after that time.
Instead of continuing the copy operation in the background (as it does not require user input...), the copy operation does not continue until I unlock the phone.
After unlocking the phone the copy operation continues, but pauses again at the next phone stand by.

**Comment by EmmanuelMess** [comment]
Ping @TranceLove.

**Comment by TranceLove** [comment]
Copying files over SFTP also uses `CopyService` under the hood... and I tried the same on Oneplus 2 running Slim7 (7.1.2) and Sony Xperia Z1 Compact running CM13 (6.0.1) too, using Amaze's current `master` and my Ubuntu workstation running OpenSSH server 7.6p1. File copy was not suspended and file was successfully saved to device.

So my next questions to ask are
* details about device, Android version, etc
* does "standby mode" means pressing the power button on the device to turn screen off and lock device?

**Comment by bugnano** [comment]
The device is a BQ Aquaris X5 running LineageOS based on Android 7.1.2

Yes, by stand by mode I mean either pressing the power button, or waiting enough time to have the device turn the screen off and lock itself automatically.

On the server side I'm using an old Fedora 20 server with openssh-server-6.4p1

When trying the same operation with FX File manager, the copy operation is much faster, and when the device is locked, the copy operation continues normally in the background, so it is not a problem neither on the server side, nor on the mobile operating system side.

**Comment by VishalNehra** [comment]
Battery optimisation is enabled by default. We should present a way for
user to disable it.
Just for sake of testing, could you try disable battery optimisation for
Amaze manually from system settings and try copying file again?

As for copying speeds, sadly it can't be improved any further.

**Comment by bugnano** [comment]
Not being able to speed up the file transfer is not a big issue.
However, I tried again copying a big file through SFTP with and without the battery optimizations for Amaze.
With the battery optimizations, after about 2 minutes of stand by, the file copy operation pauses.
Without the battery optimizations, the file copy operation fails after a few seconds.

**Comment by VishalNehra** [comment]
Will look into it.

**Comment by VishalNehra** [comment]
@zent-co could you please check this.

**Comment by zent-co** [comment]
@VishalNehra I do not have a rooted device, but I tried enabling Root Explorer preference. While I can navigate to root directory, I cannot see any system files or folders. Short of rooting my phone, is there anything else I can do to attempt to recreate the issue?

**Comment by TranceLove** [comment]
The easiest way would still be root an unused phone. [You can root an Android emulator](https://stackoverflow.com/questions/5095234/how-to-get-root-access-on-android-emulator), but the steps are clumsy and not easy to repeat.

An inexpensive solution I'd recommend LG Nexus 5x - lightweight, inexpensive (as of now), with [some caveats though](https://www.reddit.com/r/nexus5x/comments/9fvce2/comprehensive_bootloop_fix_guide_for_beginners/), but it's so cheap that you won't cry if it's broken some day.

**Comment by zent-co** [comment]
Hi @bugnano:

I believe I have this issue fixed. I was not able to reproduce your exact problem, but I did see similar issues that I fixed. Would you be willing to test out a special build that I provide to see if this is fixed on your end?

**Comment by bugnano** [comment]
Sure, just give me the apk and I'll try it

**Comment by zent-co** [comment]
Cool. I'm not sure the best way to get you the apk. Want me to email it to you? If so, send me an email at 
zent.col at gmail.com

**Comment by bugnano** [comment]
I tried the debug build and the copy operation is about twice as fast, but still not as fast as fx.
Turning on or off the battery optimization did not change the fact that the copy operation stops after 2 minutes of stand by

**Comment by zent-co** [comment]
Just to double check, does the copying operation automatically resume once the device comes out of standby? When the device comes out of standby is the notification that the server is still running in the notification panel?

**Comment by bugnano** [comment]
I confirm that the copy operation resumes after the standby

**Comment by zent-co** [comment]
And the notification is still in the notification panel? This notification states that the FTP Server is running and gives the ip address and port of the server

**Comment by VishalNehra** [comment]
This should be fixed with wakelocks at #3066

**Comment by matkoniecz** [comment]
Is still happening in v3.9

Is there changelog somewhere where I can check whether v3.9 has #3066 ?

**Comment by matkoniecz** [comment]
https://github.com/TeamAmaze/AmazeFileManager/milestone/10?closed=1 seems suggest that it was part of 3.7...

**Comment by VishnuSanal** [comment]
@VishalNehra ping
