### ISSUE TITLE
CuttyCrash : The bug where it crashes onCut

### ISSUE THREAD

**Issue by TipzTeam** [TeamAmaze/AmazeFileManager#1689]
<h1>CuttyCrash</h1>
<H2>What is it?</H2>
<P>
You are probably wondering, what does "CuttyCrash" means. It is a name I give to the bug lol. Ok, so this bug basically occurrences when you cut anything, then you delete the file you wanna cut. It will kinda crash, but no error codes and the notification bar saids that "Operation Failed".
</P>

<H2>How I discovered this bug?</H2>
<P>
I was wondering around my internal storage and deleting files. And then I suddenly click cut. "Ok, no problem. I will hit delete then". Then I hit delete twice, make it not only deleted the file, it also make the bug happen.
</P>

**Comment by bowiechen** [comment]
**Steps to reproduce**
1. Create file A.
1. Select file A to cut.
1. Delete file A.
1. Paste file A.

**Comment by bowiechen** [comment]
I would like to have a discussion on how failed file operations should be handled, as the following two cases do not have the same behavior:

**Case 1**
1. Create file `A` and `B`.
1. Select to cut `A` and `B`.
1. Delete `A`.
1. Paste files to somewhere else. 

Behavior: operation fails (prompting `A` and `B` move failed) and `B` **_is not_** moved. 

**Case 2**
1. Create file `A` and `B`.
1. Select to cut `A` and `B`.
1. Delete `B`.
1. Paste files to somewhere else. 

Behavior: operation fails (prompting `A` and `B` move failed) and `A` **_is_** moved. That is incorrect.

We can either invalidate the entire task by doing a sanity check (check if all files exist) before moving or we have to indicate that some files were moved and others weren't. The prompt text has to reflect that `A` was moved even though `B` failed.

**Comment by EmmanuelMess** [comment]
If the user does something to remove a file to be copied or cut, a toast should pop up saying that the item was removed from the copy/cut queue and will not be pasted.

If the user has deleted the file, he will see the normal delete dialog, and perhaps we should add a note on how he is deleting something that was copied.

Sanity checks should still be performed, in a way that is atomic with the paste, so we remove the possibility of some other device deleting files halfway through a paste.

**Comment by TipzTeam** [comment]
2019/11/03 Update: I made sure that I am using the latest version, but it still have the bug.

**Comment by TipzTeam** [comment]
2020/06/07 Update: this is fixed

**Comment by VishalNehra** [comment]
I'm still getting this issue. Taking this up for current release.

**Comment by TipzTeam** [comment]
Confirm fixed: 20200714
