### ISSUE TITLE
Unable to play mp4 video files SMB server

### ISSUE THREAD

**Issue by kjp4756** [TeamAmaze/AmazeFileManager#382]
Currently on beta 5.  At one point mp4 playback over smb did work (no idea which version); it was several months ago it last worked.

Choosing an mp4 video from my smb server using vlc results in vlc hanging with no video playback.  AVI files appear to play fine.  The video player doesn't matter as I have tried mplayer and had the same results.

**Comment by snow3461** [comment]
I can only confirm this problem.

**Comment by vishal0071** [comment]
I'm working on it.

**Comment by ssixty** [comment]
I can't play MKV or MP4 over SMB with the current version + MX Player or VLC.  AVI partly works in MX Player but with picture distortion and seeking isn't possible.  No issues if I launch from Solid Explorer/ES File Explorer.

Is there any information/logs/etc. I could provide that would be useful?  Thanks for your work on the app.

**Comment by vishal0071** [comment]
Fixed on v3.1.2 beta 7+

**Comment by ssixty** [comment]
@vishal0071  Afraid this is still an issue for me in 3.1.2b9,  MX Player now crashes if I seek an MKV and then crashes immediately when opening subsequent files. It returns to the beginning when seeking a MP4 (also sometimes switches to incorrect 4:3 aspect ratio).

**Comment by MarkMWright** [comment]
I'm also getting these exact problems in 3.1.2b9. I have no troubles at all with ES Explorer (other than that now being a horrendous app!)

**Comment by zin105** [comment]
Same problem here. Solid Explorer works fine for the same files that hang for Amaze.

**Comment by vishal0071** [comment]
It should be working fine now. Kindly test on MxPlayer or VLC. If still not fixed I'll need a logcat.

**Comment by zin105** [comment]
Mxplayer works fine. VLC works with other file managers but not Amaze. Anyways I've never tried logcat before, hope I did it right.

Amaze: https://pastebin.com/X9094Kk9
VLC: https://pastebin.com/1U7vAm85

Playback starts around 05-19 14:41:40.844 with the file test.mp4
