### ISSUE TITLE
Force close when going to Download folder

### ISSUE THREAD

**Issue by tuxayo** [TeamAmaze/AmazeFileManager#673]
Happened after updating from 3.1.2 RC3 to 3.1.2 RC4
It doesn't happen when with other folders.
A data clear didn't fixed the issue.

Phone: Wiko Cink Peax
Android 4.1.2
Build from F-Droid

I hadn't the time yet to find how to quickly get a logcat. I have adb setup on my computer but don't know yet how to log (and filter only to Amaze).

**Comment by vishal0071** [comment]
It should be happening only when you're downloading something. I'll be working on the fix.

**Comment by tuxayo** [comment]
It happens even without a download in progress.

Shouldn't `adb logcat 'com.amaze.filemanager*:V' '*:S'` work ? This is the output I get:

```
~ » adb logcat 'com.amaze.filemanager*:V' '*:S'
--------- beginning of /dev/log/system
--------- beginning of /dev/log/main
```

**Comment by tuxayo** [comment]
Here is the output of `adb -d logcat *:W` when the app is already openned and I click on the "Download" directory.

https://framagit.org/snippets/600

**Comment by vishal0071** [comment]
This is not the complete log, try using app like aLogcat on your device.

**Comment by vishal0071** [comment]
Go to system settings > apps > amaze > permissions and give storage permission to Amaze.

If already pressed, turn off and on.

**Comment by tuxayo** [comment]
> This is not the complete log, try using app like aLogcat on your device.

Should I still filter from the warning level? Or do you need more.

> Go to system settings > apps > amaze > permissions and give storage permission to Amaze.

On Android 4.1 one can't control this permission. It's already granted from what I understand.
Which explains why I can still go to Music and Pictures for example.

**Comment by tuxayo** [comment]
Here is the logcat when I opened Amaze from a homescreen shortcut to the download folder.(insta force close)
https://framagit.org/snippets/607

Here is the logcat when:
I cleared data.
Force stopped the app.
Started the log.
Started Amaze by the main activity.
It showed me my sd card.
Then I went to the Download folder.
Crash
Then I accepted the force close message.
Stopped logs.
https://framagit.org/snippets/608

As you can the see, the second log is only garbage. almost 100KiB of garbage. That might be aLogcat's limit (didn't found how to raise it in the settings)

Using `adb logcat '*:W' | pv > /dev/null` is measured that around ~270KiB of logs are generated during this 30 sec procedure.

**Comment by tuxayo** [comment]
Here is the logcat when:
There was no network (nor wifi nor mobile data) to limit the activity and log pollution. (it still crashes when connected to the internet)
I cleared data.
And force stopped the app.
And started the log. from my PC with `adb logcat '*:V'` (note the verbose level this time)
And started Amaze by the main activity.
Then it showed me my sd card.
When I went to the Download folder.
Then it force closed.
Then I accepted the force close message.
And stopped logging
https://framagit.org/snippets/609
↑ hurray for 700KiB of logs...

Here are some lines that might be interesting.
https://framagit.org/snippets/609#L5663
https://framagit.org/snippets/609#L5803
https://framagit.org/snippets/609#L6229

**Comment by vishal0071** [comment]
Should've been fixed with v3.2.0

**Comment by tuxayo** [comment]
Just tried quickly today when 3.2.0 came to F-Droid and I can still reproduce the issue.
Here are logs grabbed with aLogcat ROOT just after the crashes.


[alogcat.2017-08-31-11-49-47+0200.txt](https://github.com/TeamAmaze/AmazeFileManager/files/1268259/alogcat.2017-08-31-11-49-47.0200.txt)
[alogcat.2017-08-31-11-50-16+0200.txt](https://github.com/TeamAmaze/AmazeFileManager/files/1268260/alogcat.2017-08-31-11-50-16.0200.txt)

**Comment by tuxayo** [comment]
@VishalNehra Still happens with v3.2.2, request for reopening.

[logcat.txt](https://github.com/TeamAmaze/AmazeFileManager/files/2153321/logcat.txt)

**Comment by EmmanuelMess** [comment]
Extract:

```
E/AndroidRuntime( 4980): FATAL EXCEPTION: main
E/AndroidRuntime( 4980): java.lang.ArrayIndexOutOfBoundsException: length=61; index=-1
E/AndroidRuntime( 4980):        at android.text.StaticLayout.calculateEllipsis(StaticLayout.java:801)
E/AndroidRuntime( 4980):        at android.text.StaticLayout.out(StaticLayout.java:720)
E/AndroidRuntime( 4980):        at android.text.StaticLayout.generate(StaticLayout.java:428)
E/AndroidRuntime( 4980):        at android.text.StaticLayout.<init>(StaticLayout.java:140)
E/AndroidRuntime( 4980):        at android.widget.TextView.makeSingleLayout(TextView.java:5908)
E/AndroidRuntime( 4980):        at android.widget.TextView.makeNewLayout(TextView.java:5765)
E/AndroidRuntime( 4980):        at android.widget.TextView.onMeasure(TextView.java:6122)
E/AndroidRuntime( 4980):        at android.view.View.measure(View.java:15264)
E/AndroidRuntime( 4980):        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:617)
E/AndroidRuntime( 4980):        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:399)
E/AndroidRuntime( 4980):        at android.view.View.measure(View.java:15264)
E/AndroidRuntime( 4980):        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:617)
E/AndroidRuntime( 4980):        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:399)
E/AndroidRuntime( 4980):        at android.view.View.measure(View.java:15264)
E/AndroidRuntime( 4980):        at android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:8636)
E/AndroidRuntime( 4980):        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1577)
E/AndroidRuntime( 4980):        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
E/AndroidRuntime( 4980):        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
E/AndroidRuntime( 4980):        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
E/AndroidRuntime( 4980):        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
E/AndroidRuntime( 4980):        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
E/AndroidRuntime( 4980):        at android.view.View.layout(View.java:13846)
E/AndroidRuntime( 4980):        at android.view.ViewGroup.layout(ViewGroup.java:4466)
E/AndroidRuntime( 4980):        at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:636)
E/AndroidRuntime( 4980):        at android.view.View.layout(View.java:13846)
E/AndroidRuntime( 4980):        at android.view.ViewGroup.layout(ViewGroup.java:4466)
E/AndroidRuntime( 4980):        at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
E/AndroidRuntime( 4980):        at android.view.View.layout(View.java:13846)
```

This seems an error in the Android lib...

**Comment by tuxayo** [comment]
I can reproduce the same crash on an Acer Liquid E2 V370 running Android 4.2.2
Which like my Wiko Cink Peax 2 is a Mediatek MT6589/MT6588 device.

**Comment by tuxayo** [comment]
On both devices, the latest version unaffected by this crash is the 3.1.2 RC3 from F-Droid

**Comment by EmmanuelMess** [comment]
> On both devices, the latest version unaffected by this crash is the 3.1.2 RC3 from F-Droid

On version 3.3 will most probably be fixed.

**Comment by tuxayo** [comment]
I confirm that it doesn't crash anymore on 3.3.0RC13! 🎉

Thanks a lot :)
