### ISSUE TITLE
Selecting a File and Choosing Add Shortcut Does Nothing

### ISSUE THREAD

**Issue by thewizardstudio** [TeamAmaze/AmazeFileManager#955]
#### Expected Behavior
Selecting a file and choosing 'Add Shortcut' results in a Shortcut being created.

#### Actual Behavior
Selecting a file and choosing 'Add Shortcut' does not create a Shortcut and does not display an error explaining why.

#### How to Reproduce
1. Launch Amaze File Manager 3.2.1 on Android 8.1.0
2. Select a File
3. Click the 3 Vertical Dots icon at the very top right
4. Select 'Add Shortcut'

---
    Device: Pixel 2 XL
    OS: Android 8.1.0
    App Version: 3.2.1
---

#### Recording of the Bug
![Amaze_AddShortcutDoesNothing.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516311704/w2dmq1fswfyw7rs4zce3.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@thewizard.studio/selecting-a-file-and-choosing-add-shortcut-does-nothing">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by EmmanuelMess** [comment]
Already fixed in master, await update.

**Comment by matclab** [comment]
I still have the same problem in last Google play store version.
